
import { MissionWithDetails } from "@/types/mission";

export const DEMO_MISSIONS: Partial<MissionWithDetails>[] = [
  {
    id: "demo-1",
    title: "Distribution alimentaire - Secours Populaire",
    description: "Aidez-nous à distribuer des repas aux personnes en difficulté. Une action simple mais essentielle pour lutter contre la précarité alimentaire dans notre ville.",
    location: "Paris 11ème",
    duration_minutes: 120,
    start_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    format: "presentiel" as const,
    difficulty_level: "facile" as const,
    engagement_level: "ponctuel" as const,
    available_spots: 8,
    participants_count: 3,
    status: "active" as const,
    required_skills: ["Empathie", "Communication"],
    organization: {
      id: "demo-org-1",
      organization_name: "Secours Populaire Français",
      description: "Association de solidarité qui lutte contre la pauvreté et l'exclusion",
      logo_url: null,
      website_url: "https://www.secourspopulaire.fr",
      user_id: "",
      created_at: "",
      updated_at: "",
      siret_number: null,
      address: null,
      creation_date: null,
      sector_id: null,
      location: null,
      longitude: null,
      latitude: null,
    },
    mission_type: {
      id: "social",
      name: "Action sociale",
      description: "Missions d'aide sociale et de solidarité",
      created_at: "",
      updated_at: "",
    }
  },
  {
    id: "demo-2",
    title: "Nettoyage de plage - Association EcoMer",
    description: "Participez au nettoyage de la plage de Boulogne pour préserver notre environnement marin. Matériel fourni, venez nombreux !",
    location: "Boulogne-sur-Mer",
    duration_minutes: 180,
    start_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    format: "presentiel" as const,
    difficulty_level: "facile" as const,
    engagement_level: "ponctuel" as const,
    available_spots: 15,
    participants_count: 7,
    status: "active" as const,
    required_skills: ["Sensibilité environnementale"],
    organization: {
      id: "demo-org-2",
      organization_name: "EcoMer",
      description: "Protection et préservation du milieu marin",
      logo_url: null,
      website_url: null,
      user_id: "",
      created_at: "",
      updated_at: "",
      siret_number: null,
      address: null,
      creation_date: null,
      sector_id: null,
      location: null,
      longitude: null,
      latitude: null,
    },
    mission_type: {
      id: "environnement",
      name: "Environnement",
      description: "Actions pour la protection de l'environnement",
      created_at: "",
      updated_at: "",
    }
  },
  {
    id: "demo-3",
    title: "Soutien scolaire en ligne - Coup de Pouce",
    description: "Aidez des élèves de collège en mathématiques via notre plateforme en ligne. 1h par semaine, flexible selon vos disponibilités.",
    location: "À distance",
    duration_minutes: 60,
    start_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    format: "remote" as const,
    difficulty_level: "moyen" as const,
    engagement_level: "regulier" as const,
    available_spots: 5,
    participants_count: 2,
    status: "active" as const,
    required_skills: ["Mathématiques", "Pédagogie", "Patience"],
    organization: {
      id: "demo-org-3",
      organization_name: "Coup de Pouce",
      description: "Accompagnement scolaire pour tous",
      logo_url: null,
      website_url: null,
      user_id: "",
      created_at: "",
      updated_at: "",
      siret_number: null,
      address: null,
      creation_date: null,
      sector_id: null,
      location: null,
      longitude: null,
      latitude: null,
    },
    mission_type: {
      id: "education",
      name: "Éducation",
      description: "Missions d'accompagnement et de soutien éducatif",
      created_at: "",
      updated_at: "",
    }
  },
  {
    id: "demo-4",
    title: "Visite aux personnes âgées - Petits Frères",
    description: "Apportez un peu de joie et de compagnie à nos aînés isolés. Une simple conversation peut faire toute la différence.",
    location: "Lyon 3ème",
    duration_minutes: 90,
    start_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    format: "presentiel" as const,
    difficulty_level: "facile" as const,
    engagement_level: "regulier" as const,
    available_spots: 4,
    participants_count: 1,
    status: "active" as const,
    required_skills: ["Empathie", "Écoute active"],
    organization: {
      id: "demo-org-4",
      organization_name: "Les Petits Frères des Pauvres",
      description: "Lutte contre l'isolement et la solitude",
      logo_url: null,
      website_url: null,
      user_id: "",
      created_at: "",
      updated_at: "",
      siret_number: null,
      address: null,
      creation_date: null,
      sector_id: null,
      location: null,
      longitude: null,
      latitude: null,
    },
    mission_type: {
      id: "social",
      name: "Action sociale",
      description: "Missions d'aide sociale et de solidarité",
      created_at: "",
      updated_at: "",
    }
  },
  {
    id: "demo-5",
    title: "Collecte de vêtements - Emmaüs",
    description: "Participez au tri et à la collecte de vêtements pour les plus démunis. Formation sur place, ambiance conviviale garantie !",
    location: "Marseille",
    duration_minutes: 240,
    start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    format: "presentiel" as const,
    difficulty_level: "facile" as const,
    engagement_level: "ponctuel" as const,
    available_spots: 12,
    participants_count: 5,
    status: "active" as const,
    required_skills: ["Organisation", "Travail en équipe"],
    organization: {
      id: "demo-org-5",
      organization_name: "Emmaüs France",
      description: "Insertion par l'activité économique et solidarité",
      logo_url: null,
      website_url: null,
      user_id: "",
      created_at: "",
      updated_at: "",
      siret_number: null,
      address: null,
      creation_date: null,
      sector_id: null,
      location: null,
      longitude: null,
      latitude: null,
    },
    mission_type: {
      id: "social",
      name: "Action sociale", 
      description: "Missions d'aide sociale et de solidarité",
      created_at: "",
      updated_at: "",
    }
  },
  {
    id: "demo-6",
    title: "Animation atelier numérique - Centres Sociaux",
    description: "Animez un atelier d'initiation informatique pour seniors. Partagez vos connaissances numériques dans la bonne humeur.",
    location: "Toulouse",
    duration_minutes: 120,
    start_date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    format: "presentiel" as const,
    difficulty_level: "moyen" as const,
    engagement_level: "regulier" as const,
    available_spots: 3,
    participants_count: 1,
    status: "active" as const,
    required_skills: ["Informatique", "Pédagogie", "Patience"],
    organization: {
      id: "demo-org-6",
      organization_name: "Fédération des Centres Sociaux",
      description: "Animation sociale et développement local",
      logo_url: null,
      website_url: null,
      user_id: "",
      created_at: "",
      updated_at: "",
      siret_number: null,
      address: null,
      creation_date: null,
      sector_id: null,
      location: null,
      longitude: null,
      latitude: null,
    },
    mission_type: {
      id: "education",
      name: "Éducation",
      description: "Missions d'accompagnement et de soutien éducatif",
      created_at: "",
      updated_at: "",
    }
  }
];

export const DEMO_ORGANIZATIONS = [
  {
    organization_name: "Secours Populaire Français",
    description: "Association de solidarité qui lutte contre la pauvreté et l'exclusion en France et dans le monde.",
    website_url: "https://www.secourspopulaire.fr",
    address: "9-11 rue Froissart, 75003 Paris",
    sector: "Action sociale"
  },
  {
    organization_name: "EcoMer",
    description: "Association dédiée à la protection et préservation du milieu marin et des écosystèmes côtiers.",
    website_url: null,
    address: "Boulogne-sur-Mer",
    sector: "Environnement"
  },
  {
    organization_name: "Coup de Pouce",
    description: "Association d'accompagnement scolaire pour favoriser la réussite éducative de tous les enfants.",
    website_url: null,
    address: "Partout en France",
    sector: "Éducation"
  }
];

export function isDemoMode(): boolean {
  return import.meta.env.VITE_DEMO_MODE === "true" || !import.meta.env.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL === "your_supabase_url_here";
}
