// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqpcjxpbxnbrbjefkwar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxcGNqeHBieG5icmJqZWZrd2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDQ2ODMsImV4cCI6MjA2NDY4MDY4M30.DBtB4CcgKmW4BKee70uPKlfZBGssxSXrYCzTb3UOrOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);